/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package avltree;

import java.awt.HeadlessException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexander
 */
/* The JFrame Form acts as a mediator between the User and Class Array, which
   is in charge of all the hard work.
 */
public class Frm_GUI extends javax.swing.JFrame {//implements WindowConstants{

    /* Instance for Class Array is declared, yet not initialized, as its size is
       yet to be determined by the user.
     */
    AVLTree tree = new AVLTree();
    
    public Frm_GUI() 
    {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        mnuBar = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        mnuItm_addKeyb = new javax.swing.JMenuItem();
        mnuItm_addFile = new javax.swing.JMenuItem();
        mnuItm_eliminate = new javax.swing.JMenuItem();
        mnuItm_search = new javax.swing.JMenuItem();
        mnuItm_display = new javax.swing.JMenuItem();
        sep = new javax.swing.JPopupMenu.Separator();
        mnuItm_exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("8BIT WONDER", 0, 14)); // NOI18N
        lblTitle.setText("Graphic User Interface");

        txtArea.setEditable(false);
        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        menu.setText("Tools");
        menu.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                menuAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        mnuItm_addKeyb.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        mnuItm_addKeyb.setText("Add from keyboard");
        mnuItm_addKeyb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItm_addKeybActionPerformed(evt);
            }
        });
        menu.add(mnuItm_addKeyb);

        mnuItm_addFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        mnuItm_addFile.setText("Add from file");
        mnuItm_addFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItm_addFileActionPerformed(evt);
            }
        });
        menu.add(mnuItm_addFile);

        mnuItm_eliminate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        mnuItm_eliminate.setText("Eliminate one element");
        mnuItm_eliminate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItm_eliminateActionPerformed(evt);
            }
        });
        menu.add(mnuItm_eliminate);

        mnuItm_search.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnuItm_search.setText("Search one element");
        mnuItm_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItm_searchActionPerformed(evt);
            }
        });
        menu.add(mnuItm_search);

        mnuItm_display.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnuItm_display.setText("Display tree");
        mnuItm_display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItm_displayActionPerformed(evt);
            }
        });
        menu.add(mnuItm_display);
        menu.add(sep);

        mnuItm_exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mnuItm_exit.setText("Exit");
        mnuItm_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItm_exitActionPerformed(evt);
            }
        });
        menu.add(mnuItm_exit);

        mnuBar.add(menu);

        setJMenuBar(mnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       
    private void InfoMessage(String message)
    {
        JOptionPane.showMessageDialog(null, message, "", JOptionPane.INFORMATION_MESSAGE);
    }
        
    private void WarningMessage(String message)
    {
        JOptionPane.showMessageDialog(null, message, "", JOptionPane.WARNING_MESSAGE);
    }
    
    private void ErrorMessage(String message)
    {
        JOptionPane.showMessageDialog(null, message, "", JOptionPane.ERROR_MESSAGE);
    }
    
    private void menuAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_menuAncestorAdded
        // TODO add your handling code here:
        //prueba.editText("Someting something");
    }//GEN-LAST:event_menuAncestorAdded

    private void mnuItm_addKeybActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItm_addKeybActionPerformed
        
        /*if (tree.previouslyInsertedData.isEmpty())
            System.out.println("Stack's empty ya nincompoop.");
        else
            System.out.println("Stack's NOT empty ya nincompoop.");
          */  
        
        try
        {
            String[] message = new String[2];
            int num = Integer.parseInt(JOptionPane.showInputDialog(null, "Please insert an integer to be added to the AVL Tree:", "", JOptionPane.INFORMATION_MESSAGE));                        
            
            message = tree.createNode(num);
                    
            if (Boolean.parseBoolean(message[1]) == false)
                InfoMessage(message[0]);
            else
                WarningMessage(message[0]);                              
            
            //System.out.println("Inserted node: " + tree.node.data);
            
        } catch (Exception e)
        {
            if (!(e.getMessage().equals("null")))
                ErrorMessage("We're afraid that you've entered an incompatible data type.\nPlease enter an integer next time.");
                
            System.out.println("Error: " + e);
        }
        
        System.out.println("\nStack contents: " + tree.previouslyInsertedData);

    }//GEN-LAST:event_mnuItm_addKeybActionPerformed

    private void mnuItm_addFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItm_addFileActionPerformed
        // TODO add your handling code here:
        //txtArea.append("\nCompleted");
        //prueba.insertAllFromFile();
    }//GEN-LAST:event_mnuItm_addFileActionPerformed

    private void mnuItm_eliminateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItm_eliminateActionPerformed
        // TODO add your handling code here:
        //prueba.deleteOne();
    }//GEN-LAST:event_mnuItm_eliminateActionPerformed

    private void mnuItm_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItm_searchActionPerformed

        //txtArea.setText(prueba.showContents());
        //txtArea.append("" + test.Array[0]);
    }//GEN-LAST:event_mnuItm_searchActionPerformed

    private void mnuItm_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItm_exitActionPerformed
        /* Por alguna razón no me lo acepta.
         * Creo que necesitaba implementar algo, pero incluso eso no lo reconocía.
         */
        //frmGUI.setDefaultCloseOperation(Frm_GUI.EXIT_ON_CLOSE);
        //System.exit(0);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        System.exit(0);
    }//GEN-LAST:event_mnuItm_exitActionPerformed

    private void mnuItm_displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItm_displayActionPerformed

        String message = tree.print_tree(tree.root, 0);
        
        if (!(message.equals("")))
            WarningMessage(message);
        //int moves = prueba.mergesort(prueba.array);        
        //JOptionPane.showMessageDialog(null, "Los contenidos del arreglo se han ordenado exitosamente.\nEn total se realizaron " + moves + " movimientos para llevarlo a cabo.\n\nFavor de seleccionar la opción 'Show Contents' del menú con tal de ver reflejada la acción.", "Ordenamiento Mergesort exitoso", JOptionPane.INFORMATION_MESSAGE);        
    }//GEN-LAST:event_mnuItm_displayActionPerformed
             
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /*AVLTree tree = new AVLTree();
        
        System.out.println("Max(2,2): " + tree.max(2,2) + "\nMax(5,5): " + tree.max(5,5) + 
                           "\nMin(2,2): " + tree.min(2, 2) + "\nMin(4,4): " + tree.min(4, 4) +
                           "\nMin(6,5,5): " + tree.min3(6, 5, 5) +
                           "\nMin(5,6,5): " + tree.min3(5, 6, 5) + 
                           "\nMin(5,5,6): " + tree.min3(5, 5, 6) +
                           "\nMin(5,5,5): " + tree.min3(5, 5, 5));
        */
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenuItem mnuItm_addFile;
    private javax.swing.JMenuItem mnuItm_addKeyb;
    private javax.swing.JMenuItem mnuItm_display;
    private javax.swing.JMenuItem mnuItm_eliminate;
    private javax.swing.JMenuItem mnuItm_exit;
    private javax.swing.JMenuItem mnuItm_search;
    private javax.swing.JPopupMenu.Separator sep;
    public javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
